### ISSUE TITLE
MSSQL Client 4.2.0 docs is missing

### ISSUE THREAD

**Issue by tsegismont** [vertx-web-site/vertx-web-site#118]
When you browser to the Vert.x Core docs and select `4.2.0.RC1`, the docs of this version are displayed.
If you do the same with MSSQL Client, you get a 404 error page.

**Comment by michel-kraemer** [comment]
@tsegismont It seems the docs are stored at an incorrect location inside the jar artifact. This PR should fix it if I'm correct:
https://github.com/vert-x3/vertx-stack/pull/125

Please review and check if my assumption is correct.

**Comment by tsegismont** [comment]
@michel-kraemer yes indeed that was a problem.

I still don't understand why the docs for the default version would show up, but I guess they are extracted from another source.

**Comment by michel-kraemer** [comment]
@tsegismont Yes, this information is taken from the metadata js file.
